### ISSUE TITLE
should be a ITI-87 profiled bundle

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.NPFS#10]
See MHD, that has defined  a profile of Bundle for the purpose of ITI-65. 
    https://github.com/IHE/ITI.MHD/blob/master/input/fsh/provideBundle.fsh

ITI-87 should have similar profiling. This would then be referenced in place of the text on 3.87.4.1.2 that describes the Bundle.

**Comment by apinton-Arsenal** [comment]
Completed
