### ISSUE TITLE
should NOT have reference to IHE FormatCode valueSet

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.NPFS#11]
I don't think there should be a preferred binding to the IHE FormatCode, or any reference to the IHE FormatCode. The reason is that these codes are all patient specific, which NPFS is not.

Remove the dependency on ihe.formatcode valueset, and do not constrain to it.

**Comment by JohnMoehrke** [comment]
I find no references in the PDF to formatCode.

**Comment by apinton-Arsenal** [comment]
Completed
