### ISSUE TITLE
pull all NPFS artifacts from the IHE/fhir repo

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.NPFS#14]
There are many NPFS artifacts in the IHE/fhir repo 
https://github.com/IHE/fhir

All of the NPFS artifacts need to be created in your new ITI.NPFS IG, and thus in the canonical space of the ITI.NFPS IG. 

I noticed that the NPFS codesystem is not in the new IG
https://github.com/IHE/fhir/blob/master/CodeSystem/codesystem-IHE_NPFS_classcode.xml

When we publish ITI.NPFS in the IG form, we will remove these artifacts from the IHE/fhir repository.

**Comment by apinton-Arsenal** [comment]
Completed
