### ISSUE TITLE
Table 47.1-1 NPFS Profile - Actors and transactions missing

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.NPFS#17]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

47.1

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Table 47.1-1, and the paragraph above it, was not copied from the PDF to the IG. This table is responsible for declaring the transactions that the NPFS actors are required to support. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Copy the table from the PDF. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
closed with pull-request #22
