### ISSUE TITLE
Minor corruption in Volume 1

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.NPFS#18]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*
1:47.4.2.1
**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

There is some minor corruption in the first sentence:

"A technician creates a stylesheet to render the XML of CDA®[^1] Laboratory Reports produced in all the Laboratory Information System (LIS) involved in the Healthcare Information Exchange (HIE). "

It looks like the PDF referred to a footnote about CDA being a registered trademark of HL7. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Remove the bracketed reference or add a footnote with the trademark declaration. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
closed with pull-request #22
