### ISSUE TITLE
Broken link in section 2:3.87.4.1.2

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.NPFS#19]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*
2:3.87.4.1.2
**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*
The following link to DocumentReference includes a ')' in the link, so clicking it gives a 404

shall contain one FHIR DocumentReference Resource (https://www.hl7.org/fhir/R4/documentreference.html) with the file’s metadata. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Remove the trailing ')' from the link

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
closed with pull-request #22
