### ISSUE TITLE
2:3.87.4.4.2 Strange Indenting

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.NPFS#20]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*
2:3.87.4.4.2 
**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*
There is some strange indenting when describing the failure cases:

![image](https://github.com/IHE/ITI.NPFS/assets/68654017/d5d46f0c-ac37-4fd1-a542-fb529c376050)

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

I think these do not need to be indented. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
closed with pull-request #22
