### ISSUE TITLE
Reference to ITI TF-2c

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.NPFS#21]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*
1:47.4.2.2.2 
**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*
The third bullet references ITI TF-2c. Now that we are moving to web we don't use the subvolume labels anymore, I think. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Change 2c->2. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
closed with pull-request #22
